name: CMake_test

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  
  BUILD_TYPE: Release

jobs:
  build:
  
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: submodules
      run : |
        git submodule update --init --recursive
        sudo apt install lcov
        
    - name: Build
      run: cmake -H. -B _build -DCOVERAGE=1  && cmake --build _build

    - name: Test
      working-directory: ${{github.workspace}}/_build
      # Execute tests defined by the CMake configuration.  
      
      run: |
        ./test
        
        lcov -c -t "show" -o lcov.info -d .
        lcov --remove lcov.info '/home/runner/work/rk_timp/rk_timp/third-party/gtest/*' -o lcov.info
        lcov --remove lcov.info '/usr/include/*' -o lcov.info
        mkdir artifacts && cd artifacts
        du ../test >> size.txt
        
    - name: CovBeg
      uses: coverallsapp/github-action@master
      with:
          github-token: ${{ secrets.github_token }}
          path-to-lcov: ./_build/lcov.info
          coveralls-endpoint: https://coveralls.io
          
    - name: artifacts
      uses: actions/upload-artifact@v3
      with:
        name: artifacts
        path: /artifacts
